services:
  garmin-livetrack:
    build: .
    ports:
      - "3080:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REDIRECT_URI=${STRAVA_REDIRECT_URI}
